// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import * as dotenv from "dotenv";
import { defineConfig, env } from "prisma/config";

// .env.local 먼저 로드 (우선순위 높음)
dotenv.config({ path: ".env.local" });
// .env fallback
dotenv.config();

export default defineConfig({
    schema: "prisma/schema.prisma",
    migrations: {
        path: "prisma/migrations",
    },
    datasource: {
        url: env("DATABASE_URL"),
    },
});
